# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mEJsRqj3AZD1xNG1t3Zml-IEUnzDOCm
"""

def get_teams(year: int) -> List[Dict]:
  gm = Game(oauth, 'mlb')
  league_id = gm.league_ids(year = year)[0]
  lg = League(oauth, league_id)

  standings = lg.standings()
  teams = lg.teams()

  keys = []
  for i in range(len(standings)):
    key = standings[i]['team_key']
    keys.append(key)

  tm = []

  for i in range(len(keys)):
    tm.append({
        'team_key' : teams[keys[i]]['team_key'],
        'team_name' : teams[keys[i]]['name'],
        'team_logo' : teams[keys[i]]['team_logos'][0]['team_logo']['url'],
        'manager' : teams[keys[i]]['managers'][0]['manager']['nickname']
    })

  return tm

def get_week_scores(year: int, week: int) -> List[Dict]:
  gm = Game(oauth, 'mlb')
  league_id = gm.league_ids(year = year)[0]
  lg = League(oauth, league_id)

  matchup_data = lg.matchups(week = week)

  final_df = pd.DataFrame()
  data = []
  for i in range(0, 6):
    team1_key = matchup_data['fantasy_content']['league'][1]['scoreboard']['0']['matchups'][f"{i}"]['matchup']['0']['teams']['0']['team'][0][0]['team_key']
    team1_score = matchup_data['fantasy_content']['league'][1]['scoreboard']['0']['matchups'][f"{i}"]['matchup']['0']['teams']['0']['team'][1]['team_points']['total']
    team2_key = matchup_data['fantasy_content']['league'][1]['scoreboard']['0']['matchups'][f"{i}"]['matchup']['0']['teams']['1']['team'][0][0]['team_key']
    team2_score = matchup_data['fantasy_content']['league'][1]['scoreboard']['0']['matchups'][f"{i}"]['matchup']['0']['teams']['1']['team'][1]['team_points']['total']
    week = matchup_data['fantasy_content']['league'][1]['scoreboard']['0']['matchups'][f"{i}"]['matchup']['0']['teams']['0']['team'][1]['team_stats']['week']

    data.append({
        'team_key' : team1_key,
        'team_score' : team1_score,
        'week' : week})

    data.append({
        'team_key' : team2_key,
        'team_score' : team2_score,
        'week' : week})

  return data

def get_draft_results(year: int) -> List[Dict]:
  gm = Game(oauth, 'mlb')
  league_id = gm.league_ids(year = year)[0]
  lg = League(oauth, league_id)

  draft = lg.draft_results()

  return draft