# -*- coding: utf-8 -*-
"""auth_yahoo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiRnV6xYWQN_6b77I55VmAgGQBEqMKBW
"""

# auth_yahoo.py
from yahoo_oauth import OAuth2

oauth = OAuth2(None, None, from_file='oauth2.json')
print("Authentication successful!")
print("Tokens saved to oauth2.json")