# -*- coding: utf-8 -*-
"""run_once_auth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiRnV6xYWQN_6b77I55VmAgGQBEqMKBW
"""

# run_once_auth.py
from yahoo_oauth import OAuth2

# This will open a browser for you to authorize
oauth = OAuth2(None, None, from_file='oauth2.json')

# After authorization, print your tokens
print("Access Token:", oauth.access_token)
print("Refresh Token:", oauth.refresh_token)
print("\nSave these for GitHub Secrets!")